HNM RC 93 upgrdation Version 2.0

diff --git a/cgi-bin/butler/1 b/cgi-bin/butler/1
--- a/cgi-bin/butler/1
+++ b/cgi-bin/butler/1
@@ -1,17 +1,20 @@
 #!/bin/bash
-audit_task_started () {
-    echo "All Audit task on PPS which is in started"
-    echo "<br>"
-    if [ "$2" -eq "1" ]; then
-      echo '<pre>'
-       sudo /opt/butler_server/erts-9.3.3.6/bin/escript /home/gor/rpc_call.escript audittaskrec search_by "[[{'pps_id', 'equal',$1},{'status', 'equal', {'pending','started'}}], 'key']."
-       echo '</pre>'
-    elif [ "$2" -eq "2" ]; then
-      echo '<pre>'
-       sudo /opt/butler_server/erts-9.3.3.6/bin/escript /home/gor/rpc_call.escript audittaskrec search_by "[[{'pps_id', 'equal',$1},{'status', 'equal', {'pending','started'}}], 'record']."
-       echo '</pre>'
-    else 
-        echo "Wrong Key pressed"
+md_updater () {
+    bot_ip=`sudo /opt/butler_server/bin/butler_server rpcterms butlerinfo get_by_id $1. | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
+    echo "Butler Ip: $bot_ip"
+    echo "<br>" 
+    if [ ! -n "$bot_ip" ]
+    then
+        echo "Wrong Butler ID"
+    else
+        ping -c1 -W 1 $bot_ip   >/dev/null
+        if [ $? -eq 0 ];then
+	   sshpass -p 'apj0702' ssh -o StrictHostKeyChecking=no -t gor@$bot_ip "cd /data/fw/md_updater && echo 'apj0702'| sudo -S /bin/sh script.sh "
+           echo "<br>"
+           echo "OK Done..You got an ERROR.."
+        else
+           echo "Butler is not ON.....turn on Butler FIRST"
+        fi
     fi
 }
 echo "Content-type: text/html"
@@ -20,7 +23,7 @@ echo ""
 echo '<html>'
 echo '<head>'
 echo '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">'
-echo '<title>Specific audit Task on PPS for status started</title>'
+echo '<title>update mdu a Butler</title>'
 echo '</head>'
 echo '<body style="background-color:#B8B8B8">'
 
@@ -34,9 +37,8 @@ echo "<br>"
 
   echo "<form method=GET action=\"${SCRIPT}\">"\
        '<table nowrap>'\
-          '<tr><td>PPS_ID</TD><TD><input type="number" name="PPS_ID" size=12></td></tr>'\
-		  '<tr><td>Type 1 for key and 2 for record</TD><TD><input type="number" name="Type 1 for key and 2 for record" size=12></td></tr>'\
-		  '</tr></table>'
+          '<tr><td>Butler_ID</TD><TD><input type="number" name="Butler_ID" size=12></td></tr>'\
+          '</tr></table>'
 
   echo '<br><input type="submit" value="SUBMIT">'\
        '<input type="reset" value="Reset"></form>'
@@ -58,15 +60,13 @@ echo "<br>"
   else
    # No looping this time, just extract the data you are looking for with sed:
      XX=`echo "$QUERY_STRING" | sed -r 's/([^0-9]*([0-9]*)){1}.*/\2/'`
-	   YY=`echo "$QUERY_STRING" | sed -n 's/^.*record=\([^ ]*\).*$/\1/p'`
-	
-     echo "PPS_ID: " $XX
+     
+     echo "Butler_ID: " $XX
      echo '<br>'
-	   echo "Type 1 for key and 2 for record: " $YY
-     echo '<br>'
-     audit_task_started $XX $YY
+     
 
- #audit task started $XX $YY
+     md_updater $XX
+     
      
   fi
 echo '</body>'
